### ISSUE TITLE
Generate simple circos plot of Geoduck genome

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1430] opened 2022-03-09 22:35 UTC
Similar in nature to https://github.com/RobertsLab/resources/issues/772#issuecomment-551187977

using Circos (installed on Raven)

**Comment by ocattau** [comment] 2022-03-10 19:38
@kubu4  can you give an example of the code you used to generate your test figures?

**Comment by kubu4** [comment] 2022-03-10 19:47
Definitely use these tutorials - they're very thorough and kind of walk you through the general process:

http://www.circos.ca/documentation/tutorials/

The code I used:

`/home/shared/circos-0.69-9/bin/circos`

It's, in essence, that simple.

However, unseen is that it's actually using this file to create the figure:

`/home/shared/circos-0.69-9/circos.conf`

Here's what that file looks like (which is copied/pasted from the tutorials):

```
# 1.1 MINIMUM CIRCOS CONFIGURATION 
#
# This is a 'hello world' Circos tutorial. 
#
# Only required configuration elements are included.
#
# Subsequent tutorials in this section build on this example to
# generate a representative image with common elements found in Circos
# figures in the literature.

# Chromosome name, size and color definition
karyotype = data/karyotype/karyotype.human.txt

# The <ideogram> block defines the position, size, labels and other
# properties of the segments on which data are drawn. These segments
# are usually chromosomes, but can be any integer axis.

<ideogram>

<spacing>
# Spacing between ideograms. Suffix "r" denotes a relative value. It
# is relative to circle circumference (e.g. space is 0.5% of
# circumference).
default = 0.005r

# You can increase the spacing between specific ideograms.
#<pairwise hsY;hs1>
#spacing = 20r
#</pairwise>

</spacing>

# Ideogram position, thickness and fill. 
#
# Radial position within the image of the ideograms. This value is
# usually relative ("r" suffix).
radius           = 0.90r

# Thickness of ideograms, which can be absolute (e.g. pixels, "p"
# suffix) or relative ("r" suffix). When relative, it is a fraction of
# image radius.
thickness        = 20p

# Ideograms can be drawn as filled, outlined, or both. When filled,
# the color will be taken from the last field in the karyotype file,
# or set by chromosomes_colors. Color names are discussed in
#
# http://www.circos.ca/documentation/tutorials/configuration/configuration_files
#
# When stroke_thickness=0p or if the parameter is missing, the ideogram is
# has no outline and the value of stroke_color is not used.

fill             = yes  
stroke_color     = dgrey
stroke_thickness = 2p   

</ideogram>

################################################################
# The remaining content is standard and required. It is imported from
# default files in the Circos distribution.
#
# These should be present in every Circos configuration file and
# overridden as required. To see the content of these files, 
# look in etc/ in the Circos distribution.
#
# It's best to include these files using relative paths. This way, the
# files if not found under your current directory will be drawn from
# the Circos distribution. 
#
# As always, centralize all your inputs as much as possible.

<image>
# Included from Circos distribution.
<<include etc/image.conf>>                
</image>

# RGB/HSV color definitions, color lists, location of fonts, fill
# patterns. Included from Circos distribution.
#
# In older versions of Circos, colors, fonts and patterns were
# included individually. Now, this is done from a central file. Make
# sure that you're not importing these values twice by having
#
# *** DO NOT DO THIS ***
# <colors>
# <<include etc/colors.conf>>
# <colors>
# **********************
<<include etc/colors_fonts_patterns.conf>> 

# Debugging, I/O an dother system parameters
# Included from Circos distribution.
<<include etc/housekeeping.conf>> 
```

However, you'll want to use your own config file at some point. To do so, you'd issue something like the following command, where you specify the name/location of the actual config file you want to use:

```
/home/shared/circos-0.69-9/bin/circos -conf olivia.conf
```

**Comment by kubu4** [comment] 2022-03-10 19:53
Oh! Sorry! Just looked at the linked issue and had forgotten that I actually produced some stuff for the geoduck genome previously!

Hold on, let me find the repo that code is in...

**Comment by ocattau** [comment] 2022-03-16 20:16
Continuing this tread: 

Here is my .sh file to build the circos.conf file. The script will run forever on Raven without resolving when I run 
```{bash}
chmod +x karyotype.sh
sh karyotype.sh
```

karyotype.sh
```{bash
#!/bin/bash

# Script to create karyotype file for Circos

# Creates output file formatted like:
# chr - pg1 1 0 89643857 chr1

# Variables
fasta_index=${HOME}/data/generosa/Panopea-generosa-v1.0.fa
karyo_file=${HOME}/data/generosa/karyotype.pg.txt
species=pg

while IFS=$'\t' read -r line
do
	# Capture scaffold number and strip leading '0'
	scaffold_num=$(echo "${line}" | awk -F"[_\t]" '{print $2}' | sed 's/^0//')

	scaffold_length=$(echo "${line}" | awk '{print $2}')
	printf "chr - %s\n" "${species}${scaffold_num} ${scaffold_num} 0 ${scaffold_length} chr${scaffold_num}"
done < "${fasta_index}" >> "${karyo_file}"

```

**Comment by kubu4** [comment] 2022-03-16 20:18
The problem is that you're using the FastA file instead of the FastA _index_ file. FastA index file generally ends with `.fai`. For example, I'd expect the FastA index file to be this:

`Panopea-generosa-v1.0.fa.fai`

**Comment by kubu4** [comment] 2022-03-16 20:31
Sorry, just realized it's not in the Handbook! Updating that momentarily!

You can grab it from here:

https://gannet.fish.washington.edu/Atumefaciens/20191105_swoose_pgen_v074_renaming/Panopea-generosa-v1.0.fa.fai

Or, if you're so inclined, you can generate one yourself very quickly (it'll finish almost instantaeously):

```shell
cd ${HOME}/data/generosa/
samtools faidx Panopea-generosa-v1.0.fa
```

**Closed** 2023-02-22 17:59 UTC
