### ISSUE TITLE
Extract RNA from Sockeye Samples

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1307] opened 2021-10-07 21:35 UTC
Samples in the bottom of -80.

Want to extract 4 samples from each tissue to determine quality and quantity.

<img width="591" alt="IMG_4336_HEIC" src="https://user-images.githubusercontent.com/4442039/136465671-f0c5b717-8c9f-4732-9e77-f6f07e6bcd8c.png">

Prior to extracting lets confirm plan.. For example do we split samples if large tissue mass.

**Comment by kubu4** [comment] 2021-11-30 17:26
For posterity, copying Slack convo to here...

we can isolate RNA from most everything. Depends on if I should try to save some tissue for other things or use it all for RNA. Also, not sure on expected RNA yields for all of the different tissue types.
Also, a fair number of blood collected in RNAlater have cracked (they were overfilled before being frozen) and they will be particularly difficult to handle easily for RNA isolations:

![collage of examples of cracked tubes of RNAlater-preserved blood samples](https://lh3.googleusercontent.com/AiWH4nMX8pki9Vi12F18u8pjfP7iJmdapydArNHdM-6fi71FmxRJkd1BTgHx3ZoluZOvoeYnDXsEametm-IlFgeL0ilV9ja4vp5gVr8UKvXat-YGu_BEYUfF0M8oUcIVEEQnhRwJrtdJwz6G86mCEYS_8uYIIhcmjOM9sLQHQRnoTzqxm4lR6MHbF0stzNLKFZmlblA13bAWmQ4lAjgZxKWuXFfK2BCbahN4-3bc5LSP-34pjP1vGaDKBo34YP4nCoHFYvY5XvMN139EYNi93-mOR0tVDmEHoj_-WiPYK6_yJ6XAC1WiiOZaymqGr7L7YQ79JC-FEsHnIckdzOcWcJdQBuMr_TbJh0SZvPxYr-bW_5N2TBeVEGW_sf7KklB7V5r2AfSox6pe8iLqtvOPOwo7UnMW-Yos07gS6HL1eEcUFuT06X61G6SKEU-mg40gCG3SbnA0KK4madHknQ3jAcFvWR_XUjii2_CF3ezyZp_cszaXiIuL46IRmiWKT4YAknsfaGnvpMrrOJFzEc9eTyeq-ALwMCqx-gARV5cRSmpi2FppRJpRjVgYGSuSv76DPSR7rT36YdFaNDioxyw9K0Zmfn_mhiQVev7fnWf7aTkaB7msRo1CASkoyVnN7g8nuoC1FeaaHTtBbVQ-GsMqklBizyZdDuLPVRDX0n1SrjONzPsoC-K2T5Ftglq48J0hDijSh__hfVx38qJK-S6KaTLM=s1024-no?authuser=0)

I'm also not entirely sure how to handle the blood stored directly in the Vacutainers. There's a lot of blood in each container. Assuming there's a fair amount of cell lysis due to freezing, which could make it difficult to (easily) get RNA. Plus, would have to thaw entire container to allow mixing before sampling. Less than ideal, but if kept cold while thawing, would probably work.

Also, will this be for RNAseq and/or qPCR? Wouldn't need much RNA for qPCR, but would obviously need more for just RNAseq.

Would like to use TriReagent with Direct-zol kit from Zymo ($250). Can I order using money from Jackie's supply reimbursement?

**Comment by sr320** [comment] 2021-11-30 22:45
Lets plan on extracting 4
brain, liver and gonad samples. (do nothing with blood)

Does size of brain, liver and gonad samples suggest extracting whole samples or splitting?

**Comment by sr320** [comment] 2021-12-01 15:08
Likely RNA-seq and qPCR in future. 
Let proceed how you have suggested.

**Comment by kubu4** [comment] 2021-12-21 17:27
Isolated RNA from four individuals (2 in each "treatment" group):

| Sample | Tissue | Concentration (ng/uL) | Yield (ng) |
|--------|--------|-----------------------|------------|
| 2A     | brain  | 0                     | 0          |
| 2B     | liver  | 190                   | 9500       |
| 2C     | gonad  | 196                   | 9800       |
| 3A     | brain  | 0.602                 | 30.1       |
| 3B     | liver  | 186                   | 9300       |
| 3C     | gonad  | 51.8                  | 2590       |
| 23A    | brain  | 0                     | 0          |
| 23B    | liver  | 200                   | 10000      |
| 23C    | gonad  | 200                   | 20000      |
| 25A    | brain  | 20.8                  | 1040       |
| 25B    | liver  | 200                   | 20000      |
| 25C    | gonad  | 114                   | 22800      |

The biggest thing here is the poor results from the brain tissue. The other kicker is that I used the entirety of the brain for each of these individuals (to minimize heterogeneity across individuals that might be caused by inconsistent brain tissue collection and prevent introduction of heterogeneity if I were to attempt to dissect a portion of each brain tissue), so those brain samples are gone. Ugh.

I have some ideas on how isolation could be improved, so was thinking I might attempt isolations from another set of tissue sets in order to have a full "suite" of RNA from any given individual's tissue set.

What do you think?

**Comment by sr320** [comment] 2021-12-21 17:39
You mean do a couple of additional brains in order to see if yield could be improved?

**Comment by kubu4** [comment] 2021-12-21 19:17
Yes, _and_ the corresponding liver/gonad for those other individuals. Wasn't sure how this project was set up, so was thinking gene expression wanted to be compared between tissues within an individual.

**Comment by sr320** [comment] 2021-12-21 19:49
It is more - within tissue- so just two more brains would be fine

**Closed** 2022-02-08 23:18 UTC
