### ISSUE TITLE
Improve Figures for O. lurida survey paper

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#40] opened 2017-08-31 23:18 UTC
per
<img src="http://eagle.fish.washington.edu/cnidarian/skitch/Banners_and_Alerts_and_r1_MAEC_12458_review_pdf_1F58D08D.png" alt="Banners_and_Alerts_and_r1_MAEC_12458_review_pdf_1F58D08D.png"/>

---

- [ ] 49
- [ ] 50 
- [ ] 51 
- [ ] 52
- [ ] 53 
- [ ] 54
- [ ] 55
- [ ] 56
- [ ] 57
- [ ] 58
- [ ] 59
- [ ] 60
- [ ] 61
- [ ] 62

--- 
see also [r1_MAEC_12458_review.pdf](https://github.com/RobertsLab/resources/files/1268748/r1_MAEC_12458_review.pdf)

**Comment by sr320** [comment] 2017-08-31 23:23
<img src="http://eagle.fish.washington.edu/cnidarian/skitch/Banners_and_Alerts_and_r1_MAEC_12458_review_pdf__page_13_of_20__1F58D19E.png" alt="Banners_and_Alerts_and_r1_MAEC_12458_review_pdf__page_13_of_20__1F58D19E.png"/>


<img src="http://eagle.fish.washington.edu/cnidarian/skitch/r1_MAEC_12458_review_pdf__page_14_of_20__1F58D1CD.png" alt="r1_MAEC_12458_review_pdf__page_14_of_20__1F58D1CD.png"/>

**Comment by sr320** [comment] 2017-08-31 23:24
@grace-ac 
Can you provide the images you submitted?

**Comment by grace-ac** [comment] 2017-09-01 17:19
Yes! I moved out of my house yesterday and moving in today- i'll send them
as soon as i get the wifi password!

**Comment by grace-ac** [comment] 2017-09-01 19:35
I just submitted them at the end of paper. Here is the word doc with the images before they became a PDF
[OluridaSurvey_v83_clean.docx](https://github.com/RobertsLab/resources/files/1271323/OluridaSurvey_v83_clean.docx)

**Comment by sr320** [comment] 2017-09-01 19:37
But do you have the images separate on your computer?

**Comment by grace-ac** [comment] 2017-09-01 19:38
I don't believe so. I think i just kept them in the document because that's how I got them in the first place.

**Comment by grace-ac** [comment] 2017-09-01 19:39
when this all started i received a word doc of the paper with images included.

**Comment by sr320** [comment] 2017-09-01 19:40
Gotcha- thanks

**Comment by kubu4** [comment] 2017-09-06 04:35
I regenerated a subset of the figures (Figs 2 & 3). They're not exact reproductions of the figures that are in the paper. I'm guessing the in-graph annotations (those annotations highlighting high/low temps) were added in PowerPoint or something.

Any insight into this?

Personally, I think those annotations need to be added via the R script(s) to maintain the reproducibility of the repo, not from separate software.

**Comment by kubu4** [comment] 2017-09-06 18:45
Looks like annotations might not be too difficult:

http://ggplot2.tidyverse.org/reference/annotate.html

**Comment by sr320** [comment] 2017-09-06 20:02
@kubu4 can you have the code you used, - I am having trouble with a few things including working directories..

**Comment by kubu4** [comment] 2017-09-06 20:08
I followed the instructions in the repo readme and downloaded the repo as a zip file.

<em>However,</em> if you previously cloned/downloaded the repo (i.e. before last night), you'll want to re-download it, as the script for generating Figs 2 & 3 had the wrong syntax for setting the working directory. I updated the script with correct syntax last night. That might be the source of your problem.

**Comment by sr320** [comment] 2017-09-06 20:09
thanks

**Comment by sr320** [comment] 2017-09-06 20:11
jake has made edits @ https://github.com/jheare/OluridaSurvey2014
can we merge those with RobertsLab version?

**Comment by kubu4** [comment] 2017-09-06 20:20
Or, does he need to submit a pull request to our repo? I can never remember how this works! Ugh.

**Comment by kubu4** [comment] 2017-09-06 20:29
I'm in the process of merging his changes with the RobertsLab fork. However, there are some conflicts and they need to be resolved via command line (according to the GitHub website GUI).

**Comment by kubu4** [comment] 2017-09-06 20:37
Merge is completed! [RobertsLab fork](https://github.com/RobertsLab/OluridaSurvey2014) should match what exists in [Jake's repo](https://github.com/jheare/OluridaSurvey2014).

**Comment by sr320** [comment] 2017-09-06 21:40
do not worry about - not worth the effort.
I thought it might be a simple merge.

**Comment by sr320** [comment] 2017-09-06 22:10
I doubt this will cut it, but I have taken the images from Word and scaled up to 600dpi.
[Archive.zip](https://github.com/RobertsLab/resources/files/1282818/Archive.zip)

**Comment by kubu4** [comment] 2017-09-06 22:13
I thought Jake updated the figures to 600dpi?

**Comment by sr320** [comment] 2017-09-06 22:17
He has changed the some code.
I have no new figures. 
Minor - code does not include Figure 1.

**Comment by sr320** [comment] 2017-09-11 15:38
@grace-ac  can you please double check your computer for image files and also see what is available in the preprint.

**Comment by sr320** [comment] 2017-09-11 15:42
@grace-ac also evaluate how these compare to what is in proof.
http://d.pr/f/k6cxbT

**Comment by grace-ac** [comment] 2017-09-11 18:01
I have looked again, and I have no separate image files on my computer. I don't remember ever dealing with this paper's images - I just left them in as is, and maybe edited a caption or two. 

Regarding the preprint, it looks like you can only download the preprint paper, with images included. Can't find anything separate.

**Comment by grace-ac** [comment] 2017-09-11 18:03
I compared the images in: http://d.pr/f/k6cxbT to those that are in the paper version that was submitted. I have a list of comments about each image. Will include here, but basically, all images need at least one thing fixed. 

AND Figures 8-10 in the paper version that was submitted are missing from this folder. Those figures compare the mean shell length between populations over time. 


Comments on figures in the folder:
Figure 1 
F, D, and O labels are good.
M should be “C”
The “G” label does not exist in the paper version. 

Figure 2 
Figure 2 is the paper version Figure 3.
It is missing the correct site names: Northern, Southern, Central, and Hood Canal. 
Also missing the specific temperatures designated in paper version (20C Northern; 18C Central; etc.)

Figure 3 
Figure 3 is the paper version Figure 2. However, the labels are wrong - it should be Northern, Southern, Hood Canal, and Central for site names.
- It’s also missing the specific temperatures that are designated in the paper version ( -3C Hood Canal; 15C Northern, etc)

Figure 4 
Looks good, but paper version image has more square-shaped boxes, while this version has rectangular boxes.

Figure 5
Missing “Bay” after the population names on Y-axis

Figure 6
Missing “Bay” after “Dabob” and “Fidalgo” on Y-axis

Figure 7
Missing “Bay” after “Dabob” and “Fidalgo” on Y-axis

Figure 8
This should be labeled Figure 11
Otherwise, looks good

Figure 9
Should be labeled Figure 12
Y-axis should be “Month”

Figure 10
Should be labeled Figure 13
Y-axis should be “Month”

Figure 11
Should be labeled Figure 14
Site names should be Northern, Central, and Southern (L to R)

**Comment by sr320** [comment] 2017-09-11 18:18
Consider these revised
https://github.com/RobertsLab/resources/files/1282818/Archive.zip

**Comment by grace-ac** [comment] 2017-09-13 18:41
Today I will resubmit paper with the revisions, as well as upload the 600 dpi images @sr320 includes in the link above.

**Comment by grace-ac** [comment] 2017-09-13 20:03
It has been resubmitted.

**Comment by sr320** [comment] 2017-09-20 16:25
Still likely going to be issues with image quality
@grace-ac can you see if there is any figures here 
https://drive.google.com/folderview?id=0B8TM_dpSSjEsfl80MGp0TWtITHhPMHdjQlFiTVR4aEhpekJ3ZHN4bW9HektjOGpYck1kOUU

That match the paper..

**Comment by grace-ac** [comment] 2017-09-20 20:11
These figures match Figs 2, 3, 4, 11, 12, and 13 from the paper. 

Some elements are missing from 2, 3, and 4, namely: the site names should be Southern, Northern, etc.; no labeled specific temperatures that are ID'ed in the paper figures. 

Missing figures:
1, 5-10, and 14.

**Closed** 2017-10-05 09:55 UTC
