### ISSUE TITLE
Identify differentially expressed isoforms and genes in Yaamini's C.virginica data

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1252] opened 2021-07-26 16:53 UTC

**Comment by kubu4** [comment] 2021-07-26 17:14
This seems like a duplicate of this issue: https://github.com/RobertsLab/resources/issues/1249

Also, what are you envisioning here? In the issue I linked above, I've "identified" isoforms in all samples and have GTFs for all of them. What additional (if any) curation are you interested in?

**Comment by sr320** [comment] 2021-08-10 13:10
How is this going?

**Comment by kubu4** [comment] 2021-08-10 14:07
Fine. Have to dive into Ballgown.

**Closed** 2022-03-18 18:10 UTC
